[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/mklauer/nvim.git"
    refreshPeriod = "1h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "24h"
